<?php 

return array(
        'listGroups' => 'groups-management',
        'newGroupPost' => 'groups-management',
        'newGroup' => 'groups-management',
        'deleteGroup' => 'groups-management',
        'showGroup' => 'groups-management',
        'putGroup' => 'groups-management',
        'listUsers' => 'view-users-list',
        'deleteUsers' => 'delete-user',
        'newUser' => 'create-user',
        'newUserPost' => 'create-user',
        'showUser' => 'update-user-info',
        'putUser' => 'update-user-info',
        'putActivateUser' => 'update-user-info',
        'deleteUserGroup' => 'user-group-management',
        'addUserGroup' => 'user-group-management',
        'listPermissions' => 'permissions-management',
        'deletePermission' => 'permissions-management',
        'newPermission' => 'permissions-management',
        'newPermissionPost' => 'permissions-management',
        'showPermission' => 'permissions-management',
        'putPermission' => 'permissions-management',
        'addUserPermission' => 'permissions-management',
        'addGroupPermission' => 'permissions-management',
    
        'listRoomFeatures' => 'rooms-management',
        'deleteRoomFeature' => 'rooms-management',
        'newRoomFeature' => 'rooms-management',
        'newRoomFeaturePost' => 'rooms-management',
        'editRoomFeature' => 'rooms-management',
        'putRoomFeature' => 'rooms-management',
    
        'listSurcharges' => 'rooms-management',
        'deleteSurcharge' => 'rooms-management',
        'newSurcharge' => 'rooms-management',
        'newSurchargePost' => 'rooms-management',
        'editSurcharge' => 'rooms-management',
        'putSurcharge' => 'rooms-management',
    
        'listRoomTypes' => 'rooms-management',
        'deleteRoomType' => 'rooms-management',
        'newRoomType' => 'rooms-management',
        'newRoomTypePost' => 'rooms-management',
        'editRoomType' => 'rooms-management',
        'putRoomType' => 'rooms-management',
        'showRoomType' => 'rooms-management',
        'uploadRoomImage' => 'rooms-management',
    
        'listOccupancies' => 'rooms-management',
        'deleteOccupancy' => 'rooms-management',
        'newOccupancy' => 'rooms-management',
        'newOccupancyPost' => 'rooms-management',
        'showOccupancy' => 'rooms-management',
        'putOccupancy' => 'rooms-management',
    
        'listRoomPrices' => 'rooms-management',
        'deleteRoomPrice' => 'rooms-management',
        'newRoomPrice' => 'rooms-management',
        'newRoomPricePost' => 'rooms-management',
        'showRoomPrice' => 'rooms-management',
        'putRoomPrice' => 'rooms-management',
        'setRoomPrice' => 'rooms-management',
    
        'listRoomAvailabilities' => 'rooms-management',
        'deleteRoomAvailability' => 'rooms-management',
        'newRoomAvailability' => 'rooms-management',
        'newRoomAvailabilityPost' => 'rooms-management',
        'showRoomAvailability' => 'rooms-management',
        'putRoomAvailability' => 'rooms-management',
        'setRoomAvailability' => 'rooms-management',
        'table-availability' => 'rooms-management',
    
        'listRoomSurcharge' => 'rooms-management',
        'newRoomSurcharge' => 'rooms-management',
        'newRoomSurchargePost' => 'rooms-management',
        'deleteRoomSurcharge' => 'rooms-management',
        'editRoomSurcharge' => 'rooms-management',
        'updateRoomSurchargePost'=>'rooms-management',
);